### PR TITLE
Ask contributors to describe intentions

### PR DESCRIPTION
**Pull request by nsh-ableton**
We're especially interested to learn what kinds of contributions people are interested in making, and
we realized that the CLA page doesn't mention that.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
👍

**Comment by ala-ableton** [comment]
@ablbot rebase

**Comment by nsh-ableton** [comment]
@ablbot Okay, I will look at it

**Comment by nsh-ableton** [comment]
@ablbot Really, it's fine. You don't have to understand everything

**Comment by nsh-ableton** [comment]
@ablbot Now you're just repeating yourself. Wait a few minutes and I'll sort it out.

**Comment by nsh-ableton** [comment]
@ablbot merge with pr-description

**Pull request merged**
