### PR TITLE
Add Ableton_Link_SDK_License_v2.0.pdf

### PR DESCRIPTION
**Pull request by fgo-ableton**
@brs-ableton ping

### CODE REVIEW

**Comment by brs-ableton** [comment]
@fgo-ableton Did you also want to link to this?

**Comment by fgo-ableton** [comment]
@brs-ableton As we already use the new license I'll link to it.

**Comment by brs-ableton** [comment]
👍

**Comment by fgo-ableton** [comment]
@brs-ableton I also removed the old license because it is only linked to from here.

**Pull request merged**
